(eval-when-compile
  (require 'its)
  (require 'cl))

(eval-when (compile)
  (defconst its-compaction-enable t))

(defgroup greek nil
  "Greek Input Method"
  :group 'its)

(define-its-state-machine its-greek-jis-map
 "greek-jis" "Ω" Greek
 "Ελληνικα: Greek keyboard layout (JIS X0208.1983)

The layout is same as greek, but uses JIS characters.
Sorry, accents and terminal sigma are not supported in JIS."

 (its-defrule "1"  "１")
 (its-defrule "2"  "２")
 (its-defrule "3"  "３")
 (its-defrule "4"  "４")
 (its-defrule "5"  "５")
 (its-defrule "6"  "６")
 (its-defrule "7"  "７")
 (its-defrule "8"  "８")
 (its-defrule "9"  "９")
 (its-defrule "0"  "０")
 (its-defrule "-"  "−")
 (its-defrule "="  "＝")
 (its-defrule "`"  "‘")
 (its-defrule "q"  "・")
 (its-defrule "w"  "σ")
 (its-defrule "e"  "ε")
 (its-defrule "r"  "ρ")
 (its-defrule "t"  "τ")
 (its-defrule "y"  "υ")
 (its-defrule "u"  "θ")
 (its-defrule "i"  "ι")
 (its-defrule "o"  "ο")
 (its-defrule "p"  "π")
 (its-defrule "["  "［")
 (its-defrule "]"  "］")
 (its-defrule "a"  "α")
 (its-defrule "s"  "σ")
 (its-defrule "d"  "δ")
 (its-defrule "f"  "φ")
 (its-defrule "g"  "γ")
 (its-defrule "h"  "η")
 (its-defrule "j"  "ξ")
 (its-defrule "k"  "κ")
 (its-defrule "l"  "λ")
 (its-defrule ";"  "’")
 (its-defrule "'"  "’")
 (its-defrule "\\" "＼")
 (its-defrule "z"  "ζ")
 (its-defrule "x"  "χ")
 (its-defrule "c"  "ψ")
 (its-defrule "v"  "ω")
 (its-defrule "b"  "β")
 (its-defrule "n"  "ν")
 (its-defrule "m"  "μ")
 (its-defrule ","  ", ")
 (its-defrule "."  ". ")
 (its-defrule "/"  "／")
  
 (its-defrule "!"  "！")
 (its-defrule "@"  "＠")
 (its-defrule "#"  "＃")
 (its-defrule "$"  "＃")
 (its-defrule "%"  "％")
 (its-defrule "^"  "＾")
 (its-defrule "&"  "＆")
 (its-defrule "*"  "＊")
 (its-defrule "("  "（")
 (its-defrule ")"  "）")
 (its-defrule "_"  "＿")
 (its-defrule "+"  "＋")
 (its-defrule "~"  "￣")
 (its-defrule "Q"  "−")
 (its-defrule "W"  "Σ")
 (its-defrule "E"  "Ε")
 (its-defrule "R"  "Ρ")
 (its-defrule "T"  "Τ")
 (its-defrule "Y"  "Υ")
 (its-defrule "U"  "Θ")
 (its-defrule "I"  "Ι")
 (its-defrule "O"  "Ο")
 (its-defrule "P"  "Ρ")
 (its-defrule "{"  "｛")
 (its-defrule "}"  "｝")
 (its-defrule "A"  "Α")
 (its-defrule "S"  "Σ")
 (its-defrule "D"  "Δ")
 (its-defrule "F"  "Φ")
 (its-defrule "G"  "Γ")
 (its-defrule "H"  "Η")
 (its-defrule "J"  "Ξ")
 (its-defrule "K"  "Κ")
 (its-defrule "L"  "Λ")
 (its-defrule ":"  "”")
 (its-defrule "\"" "”")
 (its-defrule "|"  "｜")
 (its-defrule "Z"  "Ζ")
 (its-defrule "X"  "Χ")
 (its-defrule "C"  "Ψ")
 (its-defrule "V"  "Ω")
 (its-defrule "B"  "Β")
 (its-defrule "N"  "Ν")
 (its-defrule "M"  "Μ")
 (its-defrule "<"  "；")
 (its-defrule ">"  "：")
 (its-defrule "?"  "？"))

(define-its-state-machine its-greek-map
 "greek" ",FY" Greek
 ",FEkkgmij\: Greek keyboard layout (ISO 8859-7)
--------------

In the right of ,Fk key is a combination key, where
 ,F4 acute
 ,F( diaresis

e.g.
 ,Fa + ,F4 -> ,F\
 ,Fi + ,F( -> ,Fz
 ,Fi + ,F( + ,F4 -> ,F@"

;; 1!  2@  3#  4$  5%  6^  7&  8*  9(  0)  -_  =+  `~
;;  ,F7/  ,FrS  ,FeE  ,FqQ  ,FtT  ,FuU  ,FhH  ,FiI  ,FoO  ,FpP  [{  ]}
;;   ,FaA  ,FsS  ,FdD  ,FvV  ,FcC  ,FgG  ,FnN  ,FjJ  ,FkK  ,F4(  '"  \|
;;    ,FfF  ,FwW  ,FxX  ,FyY  ,FbB  ,FmM  ,FlL  ,;  .:  /?  

 (its-defrule "1"   "1")
 (its-defrule "2"   "2")
 (its-defrule "3"   "3")
 (its-defrule "4"   "4")
 (its-defrule "5"   "5")
 (its-defrule "6"   "6")
 (its-defrule "7"   "7")
 (its-defrule "8"   "8")
 (its-defrule "9"   "9")
 (its-defrule "0"   "0")
 (its-defrule "-"   "-")
 (its-defrule "="   "=")
 (its-defrule "`"   "`")
 (its-defrule "q"   ",F7")
 (its-defrule "w"   ",Fr")
 (its-defrule "e"   ",Fe")
 (its-defrule "r"   ",Fq")
 (its-defrule "t"   ",Ft")
 (its-defrule "y"   ",Fu")
 (its-defrule "u"   ",Fh")
 (its-defrule "i"   ",Fi")
 (its-defrule "o"   ",Fo")
 (its-defrule "p"   ",Fp")
 (its-defrule "["   "[")
 (its-defrule "]"   "]")
 (its-defrule "a"   ",Fa")
 (its-defrule "s"   ",Fs")
 (its-defrule "d"   ",Fd")
 (its-defrule "f"   ",Fv")
 (its-defrule "g"   ",Fc")
 (its-defrule "h"   ",Fg")
 (its-defrule "j"   ",Fn")
 (its-defrule "k"   ",Fj")
 (its-defrule "l"   ",Fk")
 (its-defrule ";"   ",F4")
 (its-defrule "'"   "'")
 (its-defrule "\\"  "\\")
 (its-defrule "z"   ",Ff")
 (its-defrule "x"   ",Fw")
 (its-defrule "c"   ",Fx")
 (its-defrule "v"   ",Fy")
 (its-defrule "b"   ",Fb")
 (its-defrule "n"   ",Fm")
 (its-defrule "m"   ",Fl")
 (its-defrule ","   ",")
 (its-defrule "."   ".")
 (its-defrule "/"   "/")
 
 (its-defrule "!"   "!")
 (its-defrule "@"   "@")
 (its-defrule "#"   "#")
 (its-defrule "$"   "$")
 (its-defrule "%"   "%")
 (its-defrule "^"   "^")
 (its-defrule "&"   "&")
 (its-defrule "*"   "*")
 (its-defrule "("   "(")
 (its-defrule ")"   ")")
 (its-defrule "_"   "_")
 (its-defrule "+"   "+")
 (its-defrule "~"   "~")
 (its-defrule "Q"   ",F/")
 (its-defrule "W"   ",FS")
 (its-defrule "E"   ",FE")
 (its-defrule "R"   ",FQ")
 (its-defrule "T"   ",FT")
 (its-defrule "Y"   ",FU")
 (its-defrule "U"   ",FH")
 (its-defrule "I"   ",FI")
 (its-defrule "O"   ",FO")
 (its-defrule "P"   ",FP")
 (its-defrule "{"   "{")
 (its-defrule "}"   "}")
 (its-defrule "A"   ",FA")
 (its-defrule "S"   ",FS")
 (its-defrule "D"   ",FD")
 (its-defrule "F"   ",FV")
 (its-defrule "G"   ",FC")
 (its-defrule "H"   ",FG")
 (its-defrule "J"   ",FN")
 (its-defrule "K"   ",FJ")
 (its-defrule "L"   ",FK")
 (its-defrule ":"   ",F(")
 (its-defrule "\""  "\"")
 (its-defrule "|"   "|")
 (its-defrule "Z"   ",FF")
 (its-defrule "X"   ",FW")
 (its-defrule "C"   ",FX")
 (its-defrule "V"   ",FY")
 (its-defrule "B"   ",FB")
 (its-defrule "N"   ",FM")
 (its-defrule "M"   ",FL")
 (its-defrule "<"   ";")
 (its-defrule ">"   ":")
 (its-defrule "?"   "?")
 
 (its-defrule "a;"  ",F\")
 (its-defrule "e;"  ",F]")
 (its-defrule "h;"  ",F^")
 (its-defrule "i;"  ",F_")
 (its-defrule "o;"  ",F|")
 (its-defrule "y;"  ",F}")
 (its-defrule "v;"  ",F~")
 (its-defrule "A;"  ",F6")
 (its-defrule "E;"  ",F8")
 (its-defrule "H;"  ",F9")
 (its-defrule "I;"  ",F:")
 (its-defrule "O;"  ",F<")
 (its-defrule "Y;"  ",F>")
 (its-defrule "V;"  ",F?")
 (its-defrule "i:"  ",Fz")
 (its-defrule "y:"  ",F{")
 (its-defrule "I:"  ",FZ")
 (its-defrule "Y:"  ",F[")
 (its-defrule "i:;" ",F@")
 (its-defrule "y:;" ",F`"))

(provide 'its/greek)
